

spring:
  application:
    name: attendance
  datasource:
    url: jdbc:mysql://localhost:3306/efficient
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  freemarker:
#    template-loader-path: classpath:/templates
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .ftl

server:
  port: 10927

mybatis:
  typeAliasesPackage: com.newness.efficient.*.entity
  mapperLocations: classpath:com/newness/efficient/attendance/*/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
#  params: count=countSql

logging:
  level:
    com.newness.efficient.attendance: debug
#  config: classpath:log4j2.yml



token:
  duration: 2 * 60 * 60 * 1000